### PR TITLE
Added configuration scripts for raspberry pi setup

### PR DESCRIPTION
**Pull request by zhiquanyeo**

### CODE REVIEW

**Comment by zhiquanyeo** [comment]
We'll also need to copy the `wpilibws-romi.service` file into `/etc/systemd/system` and then run `sudo systemctl enable wpilibws-romi.service` (and the corresponding service start call)

**Comment by jpokornyiii** [comment]
Tested script on fresh piOS install. Looked good.

**Comment by jpokornyiii** [comment]
Could we add i2c enablement? I believe it's just flipping a line in /boot/config.txt:
<code>#dtparam=i2c_arm=on</code>
to
<code>dtparam=i2c_arm=on</code>

**Comment by jpokornyiii** [comment]
Not sure if we want to check this in first, but with the service file, we should be able to do something like:
<code>wget -P /etc/systemd/system/ https://raw.githubusercontent.com/wpilibsuite/wpilib-ws-robot-romi/master/scripts/wpilibws-romi.service</code>
<code>sudo systemctl enable wpilibws-romi.service</code>

Also, thoughts on changing the name of the folder to "install" or "download" for anything we will need to pull down in order to distinguish the files we need specifically for install?

**Comment by zhiquanyeo** [comment]
No longer needed

**Pull request closed without merging**
