### PR TITLE
feature: Data StreamFilter-s + Gyro rate smoothing

### PR DESCRIPTION
**Pull request by zhiquanyeo**

### CODE REVIEW

**Comment by jpokornyiii** [comment]
Why did you create a FilterChain class? Doesn't seem to be needed here.

**Comment by jpokornyiii** [comment]
Rest of this looks good.

**Comment by zhiquanyeo** [comment]
> Why did you create a FilterChain class? Doesn't seem to be needed here.

Was a little bit of forward planning, in case we needed to string together a bunch of filters

**Comment by jpokornyiii** [comment]
I hear you, but we might not need it as well. To keep the code base clean, shouldn't we add it only when it becomes necessary?

**Pull request merged**
